variables:
  Horton.FrameworkRoot: $(Agent.BuildDirectory)/e2e-fx
  Horton.FrameworkRef: node-gate-1
  Horton.Language: node
  Horton.Repo: Azure/azure-iot-sdk-node
  Horton.Commit: $(Build.SourceBranch)
  Horton.ForcedImage: ''

resources:
  repositories:
  - repository: e2e_fx
    type: github
    name: Azure/iot-sdks-e2e-fx
    ref: node-gate-1
    endpoint: 'e2e-fx-github-access'

jobs:
- template: vsts/templates/jobs-build-ci.yaml@e2e_fx

  
